name: Node.js CI

on:
  push:
      branches-ignore: main
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

    - name: Copy Node bindings dll
      run: ./copy_tfjs_bindings.bat

    - run: npx eslint --max-warnings 0 src

    - run: npm run build-minimal-esm
      env:
        CI: true
    - run: npm run test-no-coverage