name: Publish to npm

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - run: echo 'script version 00011'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org/'
#NOTE: This url (^^) unintuitively is not where our package lives. However, do
#      not update it to "https://www.npmjs.com/package/". I tried that, and it
#      caused the next step ('Install dependencies') to overflow the stack (on
#      the GitHub build VM).

    - name: Install dependencies
      run: npm install

    - run: npm run build-no-doc

    - name: Set user email
      run: git config user.email "joemullenix@hotmail.com"

    - name: Set user name
      run: git config user.name "Joe Mullenix"

#NOTE: Previous editions bumped the npm semver here. However, that led to pain,
#      both pre and post release. Our package.json did _not_ get the changes
#      made by the script run, so we ended up behind the live version. Also,
#      that meant we had to remember to bump ourselves up to the future semver
#      _before_ comitting. Also also, we couldn't use sensible version tags
#      on draft releases, because it caused conflicts when the script tried to
#      create the exact same tag mid-run.
#      It all sucked, for very little gain, so now we bump pre-commit.
#TODO: ...but find a way to automate it! It's likely worth whatever tradeoffs.

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.SECRET_PUBLISH_NPM }}
