name: Publish to npm

on:
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - name: Print script version
      run: echo '008'

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm install

    - run: npm run build-no-doc

    - name: Set user email
      run: git config user.email "joemullenix@hotmail.com"

    - name: Set user name
      run: git config user.name $GITHUB_ACTOR

    - name: Bump version
      run: npm version patch

    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.SECRET_PUBLISH_NPM }}
