name: Node.js CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install

    - name: Run linters
      run: npx eslint src
    # - name: Run linters
    #   uses: wearerequired/lint-action@v1
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     # Enable linters
    #     eslint: true

    - run: npm run build-minimal-esm
      env:
        CI: true
    - run: npm run test-no-coverage